spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

logging.level.org.springframework.batch: DEBUG
logging.level.org.org.hibernate.SQL: debug

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/querydsl
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: validate

logging.level:
  org.springframework.batch: DEBUG
  org.hibernate.SQL: debug
